name: Proxmox Container Management

on:
  push:
    branches: ["**"]
  create:
  delete:

jobs:
  setup-runner:
    runs-on: ubuntu-latest
    if: github.event_name != 'push' || github.event.created == false
    steps:
      - name: Install Dependencies
        run: |
          sudo apt install -y sshpass jq
      - uses: maxklema/proxmox-launchpad@test
        with:
          proxmox_password: ${{ secrets.PROXMOX_PASSWORD }}
          proxmox_username: ${{ secrets.PROXMOX_USERNAME }}
          github_pat: ${{ secrets.GH_PAT }}
  manage-container:
    runs-on: self-hosted
    needs: setup-runner
    if: github.event_name != 'push' || github.event.created == false
    steps:
      - uses: maxklema/proxmox-launchpad@test
        with:
          proxmox_password: ${{ secrets.PROXMOX_PASSWORD }}
          proxmox_username: ${{ secrets.PROXMOX_USERNAME }}
          public_key: ${{ secrets.PUBLIC_KEY }}
          container_env_vars: '{"API_KEY": "1234"}'
          install_command: npm i
          start_command: npm start
          runtime_language: nodejs
          services: '["mongodb"]'
          custom_services: '[["sudo apt-get update", "sudo apt install nginx", "sudo systemctl enable nginx", "sudo systemctl start nginx"]]'
