name: Proxmox Container Management

on:
  push:
  create:
  delete:

jobs:
  setup-runner:
    runs-on: ubuntu-latest
    steps:
      - name: Install Dependencies
        run: |
          sudo apt install -y sshpass jq
      - uses: maxklema/proxmox-launchpad@test-2
        with:
          proxmox_password: ${{ secrets.PROXMOX_PASSWORD }}
          proxmox_username: ${{ secrets.PROXMOX_USERNAME }}
          github_pat: ${{ secrets.GH_PAT }}
  manage-container:
    runs-on: self-hosted
    needs: setup-runner
    steps:
      - uses: maxklema/proxmox-launchpad@test-2
        with:
          proxmox_password: ${{ secrets.PROXMOX_PASSWORD }}
          proxmox_username: ${{ secrets.PROXMOX_USERNAME }}
          public_key: ${{ secrets.PUBLIC_KEY }}
          github_pat: ${{ secrets.GH_PAT }}
          container_env_vars: '{"API_KEY": "1234"}'
          install_command: npm i
          http_port: 120000
          start_command: npm start
          runtime_language: nodejs
          services: '["mongodb"]'
