# .github/workflows/proxmox.yml
name: Proxmox Container Management

on:
  push:
    branches: ["**"]
  create:
  delete:

jobs:
  setup-runner:
    runs-on: ubuntu-latest
    if: github.event_name != 'push' || github.event.created == false
    steps:
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y sshpass jq

      - uses: maxklema/mie-opensource-action@main
        with:
          github_event_name: ${{ github.event_name }}
          github_repository: ${{ github.event.repository.name }}
          github_repository_owner: ${{ github.repository_owner }}
          github_ref_name: ${{ github.event.ref }}
          proxmox_password: ${{ secrets.PROXMOX_PASSWORD }}
          proxmox_username: mklema
          container_password: ${{ secrets.CONTAINER_PASSWORD }}
          http_port: 32000
          linux_distribution: debian
          github_pat: ${{ secrets.GH_PAT }}
          create_runner_job: y
  manage-container:
    runs-on: self-hosted
    needs: setup-runner
    if: github.event_name != 'push' || github.event.created == false
    steps:
      - uses: maxklema/mie-opensource-action@main
        with:
          github_event_name: ${{ github.event_name }}
          github_repository: ${{ github.event.repository.name }}
          github_repository_owner: ${{ github.repository_owner }}
          github_ref_name: ${{ github.event.ref }}
          proxmox_password: ${{ secrets.PROXMOX_PASSWORD }}
          proxmox_username: mklema
          container_password: ${{ secrets.CONTAINER_PASSWORD }}
          http_port: 32000
          linux_distribution: debian
          public_key: ${{ secrets.PUBLIC_KEY }}
          deploy_on_start: y
          require_env_vars: y
          container_env_vars: '{"API_KEY": "1234"}'
          install_command: npm i
          build_command:
          start_command: npm start
          runtime_language: nodejs
          require_services: y
          services: '["mongodb"]'
          custom_services:
          github_pat: ${{ secrets.GH_PAT }}
          create_runner_job: n
