name: Proxmox Deployment

on: 
    push:
    create:
    delete:
  
jobs:
    setup-runner:
        runs-on: ubuntu-latest
        steps:
          - name: Install Dependencies
            run: |
              sudo apt install -y sshpass jq
          - uses: maxklema/proxmox-launchpad@main
            with:
              proxmox_username: mklema
              proxmox_password: ${{ secrets.PROXMOX_PASSWORD }}
              github_pat: ${{ secrets.GH_PAT }}
    deploy:
        runs-on: ubuntu-latest
        needs: setup-runner
        steps:
          - name: Install Dependencies
            run: |
             sudo apt-get update
              sudo apt install -y sshpass jq
          - name: Deploy to Proxmox
            uses: maxklema/proxmox-launchpad@main
            with: 
                proxmox_username: mklema
                proxmox_password: ${{ secrets.PROXMOX_PASSWORD }}
                container_env_vars: '{"API_KEY": "your-api-key-2", "NODE_ENV": "production-2"}'
                github_pat: ${{ secrets.GH_PAT }}
                http_port: 32000
                install_command: npm install
                start_command: npm run start
                runtime_language: nodejs
                services: '["mongodb"]'

                
